# Generated by Django 4.1 on 2024-07-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fName", models.CharField(max_length=30)),
                ("lname", models.CharField(max_length=30)),
                ("stars", models.IntegerField()),
            ],
        ),
    ]
