# Generated by Django 4.1 on 2024-07-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("office", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="heart",
            field=models.IntegerField(default=73),
        ),
    ]
