# Generated by Django 4.1 on 2024-07-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Teachers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fName", models.CharField(max_length=30)),
                ("lname", models.CharField(max_length=30)),
                ("subject", models.CharField(max_length=30)),
            ],
        ),
    ]
