# Generated by Django 4.1 on 2024-07-29 19:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("classroom", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Teachers",
            new_name="Teacher",
        ),
    ]
